# Generated by Django 4.1.6 on 2023-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='EMAIL')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='EMAIL')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('password', models.CharField(max_length=100, verbose_name='PASSWORD')),
                ('is_admin', models.BooleanField(default=False, verbose_name='IS_ADMIN')),
            ],
        ),
    ]
