# Generated by Django 4.1.6 on 2023-02-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailHistory',
        ),
    ]
