# Generated by Django 4.1.6 on 2023-02-06 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('image', models.ImageField(blank=True, null=True, upload_to='snack/', verbose_name='IMAGE')),
                ('url', models.URLField(help_text='구매 URL', max_length=400, verbose_name='URL')),
                ('description', models.CharField(blank=True, help_text='간식에 대한 설명', max_length=300, verbose_name='DESCRIPTION')),
                ('state', models.CharField(default='waiting', max_length=50, verbose_name='STATE')),
                ('arrive_month', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='ARRIVE_MONTH')),
            ],
        ),
    ]
