# Generated by Django 4.1.6 on 2023-02-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0008_alter_snack_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={'ordering': ('create_dt',), 'verbose_name': 'snack', 'verbose_name_plural': 'snacks'},
        ),
    ]
