# Generated by Django 4.1.6 on 2023-02-08 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0010_alter_snack_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='arrive_month',
        ),
        migrations.AddField(
            model_name='snack',
            name='supply_month',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='SUPPLY_MONTH'),
        ),
    ]
