# Generated by Django 4.1.6 on 2023-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0011_remove_snack_arrive_month_snack_supply_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='modify_dt',
        ),
    ]
