# Generated by Django 4.1.6 on 2023-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0012_remove_snack_modify_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='supply_year',
            field=models.PositiveSmallIntegerField(default=2023, null=True, verbose_name='SUPPLY_YEAR'),
        ),
    ]
