# Generated by Django 4.1.6 on 2023-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0013_snack_supply_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(upload_to='snack/images/', verbose_name='IMAGE'),
        ),
    ]
