# Generated by Django 4.1.6 on 2023-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0014_alter_snack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='supply_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='SUPPLY_YEAR'),
        ),
    ]
