# Generated by Django 4.1.6 on 2023-03-07 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0015_alter_snack_supply_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={'ordering': ('-id',), 'verbose_name': 'snack', 'verbose_name_plural': 'snacks'},
        ),
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.CharField(blank=True, help_text=' 예) 5개 주문해주세요!', max_length=300, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='supply_month',
            field=models.PositiveSmallIntegerField(help_text=' 예) 7', null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='SUPPLY_MONTH'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='supply_year',
            field=models.PositiveSmallIntegerField(help_text=' 예) 2023', null=True, verbose_name='SUPPLY_YEAR'),
        ),
    ]
