# Generated by Django 4.1.6 on 2023-03-08 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0017_alter_snack_options_snackrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snackrequest',
            options={'ordering': ['-id'], 'verbose_name': 'snack_request', 'verbose_name_plural': 'snack_requests'},
        ),
        migrations.RemoveField(
            model_name='snack',
            name='create_dt',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='description',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='supply_month',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='supply_year',
        ),
        migrations.AlterField(
            model_name='snackrequest',
            name='supply_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text=' 예) 7', null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='SUPPLY_MONTH'),
        ),
        migrations.AlterField(
            model_name='snackrequest',
            name='supply_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text=' 예) 2023', null=True, verbose_name='SUPPLY_YEAR'),
        ),
        migrations.AlterModelTable(
            name='snackrequest',
            table='snack_snack_requests',
        ),
    ]
