# Generated by Django 4.1.6 on 2023-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0018_alter_snackrequest_options_remove_snack_create_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='NAME'),
        ),
    ]
