# Generated by Django 4.1.6 on 2023-03-09 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snack', '0019_alter_snack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snackrequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
