# Generated by Django 4.1.6 on 2023-03-10 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snack', '0020_alter_snackrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackrequest',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snackRequests', to='snack.snack'),
        ),
        migrations.AlterField(
            model_name='snackrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snackRequests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SnackEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('snack_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snackEmotions', to='snack.snackrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snackEmotions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
