# Generated by Django 4.1.6 on 2023-03-16 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0023_alter_snackemotion_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackrequest',
            name='supply_month',
            field=models.IntegerField(blank=True, help_text=' 예) 7', null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='SUPPLY_MONTH'),
        ),
        migrations.AlterField(
            model_name='snackrequest',
            name='supply_year',
            field=models.IntegerField(blank=True, help_text=' 예) 2023', null=True, verbose_name='SUPPLY_YEAR'),
        ),
    ]
