# Generated by Django 4.1.6 on 2023-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack', '0024_alter_snackrequest_supply_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackrequest',
            name='supply_year',
            field=models.IntegerField(blank=True, help_text=' 예) 2023', verbose_name='SUPPLY_YEAR'),
        ),
    ]
